name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish App
        run: dotnet publish BlazorApp/BlazorApp.csproj -c Release -o release

      - name: Change base-tag in index.html from / to repository name
        run: sed -i 's/<base href="\/" \/>/<base href="\/${{ github.event.repository.name }}\/" \/>/g' release/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit and Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
          token: ${{ secrets.GITHUB_TOKEN }}
